apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfheal-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selfheal-app
  template:
    metadata:
      labels:
        app: selfheal-app
    spec:
      containers:
      - name: selfheal-app
        image: nikshithakompally/selfheal-app:v6   # ✅ update tag each time you rebuild
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
