pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('dockerhub-creds')
        IMAGE_NAME = "aksh230570/self-healing-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Aksh230570/Self-App.git'
            }
        }

        stage('Clean Old Docker Image') {
            steps {
                script {
                    bat """
                        docker rmi -f %IMAGE_NAME%:latest || echo "No previous image"
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat """
                        docker build --no-cache -t %IMAGE_NAME%:latest self-healing-app/
                    """
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    bat """
                        echo %DOCKERHUB_PSW% | docker login -u %DOCKERHUB_USR% --password-stdin
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    bat """
                        docker push %IMAGE_NAME%:latest
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo "To deploy manually, run:"
                echo "kubectl apply -f self-healing-app/k8s/"
            }
        }
    }
}
